modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"

[[mods]]
modId = "furniture"
version = "${version}"
displayName = "[Let's Do] Furniture"
authors = "berksire, satisfy, cph101"
icon = "pack.png"
description = '''
Let's expand your world with a whole set of new and exciting furnitures! All in the style of the Let's Do Mods.
'''

[[dependencies.furniture]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.80,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.furniture]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.furniture]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"
